name: Building-and-testing-workflow
on: [ push ]
jobs:
  Building:
    runs-on: [self-hosted, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/recreate_build.sh