name: Building-and-testing-workflow
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Building:
    name: Build AES library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building library
        run: |
          mkdir build
          cd build
          cmake ..
          make AES

  Testing:
    name: Run tests of AES
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build library and tests
        run: |
          mkdir build
          cd build
          cmake -DTESTING=ON ..
          make
      - name: Run StateTests
        run: |
          cd build
          ./StateTests
      - name: Run KesScheduleTests
        run: |
          cd build
          ./KeyScheduleTests
      - name: Run RijndaelTests
        run: |
          cd build
          ./RijndaelTests

  ValgrindCheck:
    name: Memory leaks searching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run valgrind checks
        run: ./scripts/valgrind-check.sh

  CppCheck:
    name: Cppcheck executing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cppcheck
        run: sudo apt install cppcheck
      - name: Check project directory
        run: cppcheck project
  CodeCoverage:
    name: Report code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build tests and generate coverage report
        run: ./scripts/coverage-report.sh
      - name:  Getting code coverage data
        uses: codecov/codecov-action@v2
        with:
          token: ff897e5c-ceb7-4d09-bf59-0b98873ba7fc
          files: coverage.xml
