name: Building-and-testing-workflow
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Building:
    name: Build AES library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building library
        run: |
          mkdir build
          cd build
          cmake ..
          make AES
