name: Building-and-testing-workflow
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Building:
    name: Build AES library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building library
        run: |
          mkdir build
          cd build
          cmake ..
          make AES

  Testing:
    name: Run tests of AES
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build library and tests
        run: |
          mkdir build
          cd build
          cmake -DTESTING=ON ..
          make
      - name: Run StateTests
        run: |
          cd build
          ./StateTests
      - name: Run KesScheduleTests
        run: |
          cd build
          ./KeyScheduleTests
      - name: Run RijndaelTests
        run: |
          cd build
          ./RijndaelTests

  CodeCoverage:
    name: Report code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build tests and generate coverage report
        run: |
          pwd
          ls -la
          ls -la scripts
          ./scripts/coverage-report.sh
      - name:  Getting code coverage data
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
